import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Resume Builder",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <>
      <h2>Resume Builder Layout</h2>
      {children}
    </>
  );
}
