import type { Metadata } from "next";
import Sidebar from "../components/Sidebar";
import Button from "../components/ui/Button";

export const metadata: Metadata = {
  title: "Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <div className="min-w-[220mm] min-h-[330mm] grid place-items-center bg-gray-400">

      <div className="w-[210mm] flex justify-around items-center pt-4">
        <h2 className="w-5/6 text-4xl font-bold text-light">Resume Layout</h2>
        <Button
          className="w-1/6 h-10 bg-primary text-white"
          >
          Edit
        </Button>
      </div>

      {/* A4 Size (210 x 297 mm) (793.70 x 1122.51 px) */}
      <div
        className="w-[210mm] h-[297mm] overflow-hidden rounded-md bg-white shadow-lg"
      >
        <div className="resume h-full flex">
          <div className="w-1/3">
            <Sidebar/>
          </div>
          <div className="w-2/3">
            {children}
          </div>
        </div>
      </div>
    </div>
  );
}
