import type { Metadata } from "next";
import Sidebar from "../components/Sidebar";

export const metadata: Metadata = {
  title: "Resume",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <div className="grid min-h-screen place-items-center bg-gray-400">
      <h2 className="text-4xl font-bold text-light py-4">Resume Layout</h2>
      <div
        className="flex m-4 h-[297mm] w-[210mm] overflow-hidden rounded-md bg-white shadow-lg"
      >
        <div className="w-1/3">
          <Sidebar/>
        </div>
        <div className="w-2/3">
          {children}
        </div>
      </div>
    </div>
  );
}
